---
title: "Benchmarking parallel predictions 2022"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Benchmarking parallel predictions 2022}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(mlr3spatial)
library(mlr3learners)
library(future, exclude = "values")
library(terra, exclude = "resample")
```

Task Train

```{r}
stack = generate_stack(list(
    numeric_layer("x_1"),
    numeric_layer("x_2"),
    numeric_layer("x_3"),
    numeric_layer("x_4"),
    factor_layer("y", levels = c("a", "b"))),
  layer_size = 10
)
vector = sample_vector(stack, n = 1000)
task_train = as_task_classif(as_data_backend(vector), id = "train", target = "y")
```

Task Predict

```{r}
stack[["y"]] = NULL
task_predict = as_task_classif(as_data_backend(stack, train_task = task_train), id = "train", target = "y")
```

# Benchmark

## 1 Core

mlr3 and terra can use 1 core and xgboost 4

Learner

```{r}
learner = lrn("classif.ranger", num.threads = 4)
learner$train(task_train)
```

Terra Wrapper

```{r}
predfun = function(model, data) {
  predict(model, data, num.threads = 4)$predictions
}

model = learner$model
```

```{r}
bm = bench::mark(

  "01-mlr3-1-core" = {
    plan(sequential)
    predict_spatial(task_predict, learner, chunksize = 10L)
  },

  "02-terra-1-core" = {
    terra::predict(stack, model, fun = predfun)
  },

  check = FALSE, filter_gc = FALSE, min_iterations = 1,
  max_iterations = 1, memory = FALSE)
```

## 4 Cores

Learner

```{r}
learner = lrn("classif.ranger", num.threads = 1)
learner$parallel_predict = TRUE
learner$train(task_train)
```

Terra Wrapper

```{r}
predfun = function(model, data) {
  predict(model, data, num.threads = 1)$predictions
}

model = learner$model
```

```{r}
bm = bench::mark(

  "01-mlr3-4-cores" = {
    plan(multicore, workers = 4)
    predict_spatial(task_predict, learner, chunksize = 10L)
  },

  "02-terra-4-core" = {
    terra::predict(stack, model, fun = predfun, cores = 4, cpkgs = "ranger")
  },

  check = FALSE, filter_gc = FALSE, min_iterations = 1,
  max_iterations = 1, memory = FALSE)
```
